# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

temperature <- function(h, profile, profile_pars) {
    .Call(`_estDLVM_temperature`, h, profile, profile_pars)
}

LC_em_step <- function(Y, yv, C, ns, r, n, k, piv, Piv, Psi, Phi) {
    .Call(`_estDLVM_LC_em_step`, Y, yv, C, ns, r, n, k, piv, Piv, Psi, Phi)
}

LC_tem_step <- function(Y, yv, C, ns, r, n, k, piv, Piv, Psi, Phi, temp) {
    .Call(`_estDLVM_LC_tem_step`, Y, yv, C, ns, r, n, k, piv, Piv, Psi, Phi, temp)
}

LC_em <- function(Y, yv, k, tol, maxit, piv, Piv, Psi, Phi) {
    .Call(`_estDLVM_LC_em`, Y, yv, k, tol, maxit, piv, Piv, Psi, Phi)
}

LC_tem <- function(Y, yv, k, tol, maxit, piv, Piv, Psi, Phi, profile, profile_pars) {
    .Call(`_estDLVM_LC_tem`, Y, yv, k, tol, maxit, piv, Piv, Psi, Phi, profile, profile_pars)
}

Initialization_step_C <- function(Y, yv, ns, r, C, k, n_parents) {
    .Call(`_estDLVM_Initialization_step_C`, Y, yv, ns, r, C, k, n_parents)
}

MaxExp_step_C <- function(Y, yv, ns, n, r, C, V, k, R, tol) {
    .Call(`_estDLVM_MaxExp_step_C`, Y, yv, ns, n, r, C, V, k, R, tol)
}

LastMaxExp_step_C <- function(Y, yv, ns, n, r, C, V, k, R, tol) {
    .Call(`_estDLVM_LastMaxExp_step_C`, Y, yv, ns, n, r, C, V, k, R, tol)
}

CrossOver_step_C <- function(ns, P, n_children, n_parents) {
    .Call(`_estDLVM_CrossOver_step_C`, ns, P, n_children, n_parents)
}

Selection_step_C <- function(PV_p, PV_c, fit_p, fit_c, n_parents, n_children) {
    .Call(`_estDLVM_Selection_step_C`, PV_p, PV_c, fit_p, fit_c, n_parents, n_children)
}

Mutation_step_C <- function(ns, k, V, prob_mut) {
    .Call(`_estDLVM_Mutation_step_C`, ns, k, V, prob_mut)
}

LC_eem <- function(Y, yv, k, tol, maxit, n_parents, n_children, prob_mut, R) {
    .Call(`_estDLVM_LC_eem`, Y, yv, k, tol, maxit, n_parents, n_children, prob_mut, R)
}

