# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HMcat_Temperature <- function(h, profile, profile_pars) {
    .Call(`_estDLVM_HMcat_Temperature`, h, profile, profile_pars)
}

HMcat_ComputeLogLik <- function(S, yv, piv, Pi, Phi) {
    .Call(`_estDLVM_HMcat_ComputeLogLik`, S, yv, piv, Pi, Phi)
}

HMcat_CheckConvergence <- function(lk, lk_old, piv, Pi, Phi, piv_old, Pi_old, Phi_old, it, tol_lk, tol_theta, maxit) {
    .Call(`_estDLVM_HMcat_CheckConvergence`, lk, lk_old, piv, Pi, Phi, piv_old, Pi_old, Phi_old, it, tol_lk, tol_theta, maxit)
}

HMcat_E_step <- function(yv, ns, TT, k, llk_list, Pi) {
    .Call(`_estDLVM_HMcat_E_step`, yv, ns, TT, k, llk_list, Pi)
}

HMcat_TE_step <- function(yv, ns, TT, k, llk_list, Pi, temp) {
    .Call(`_estDLVM_HMcat_TE_step`, yv, ns, TT, k, llk_list, Pi, temp)
}

HMcat_M_step <- function(Sv, n, ns, r, TT, k, Cv, C, E_list, modBasic) {
    .Call(`_estDLVM_HMcat_M_step`, Sv, n, ns, r, TT, k, Cv, C, E_list, modBasic)
}

HMcat_EM <- function(S, yv, k, tol_lk, tol_theta, maxit, piv, Pi, Phi, modBasic) {
    .Call(`_estDLVM_HMcat_EM`, S, yv, k, tol_lk, tol_theta, maxit, piv, Pi, Phi, modBasic)
}

HMcat_TEM <- function(S, yv, k, tol_lk, tol_theta, maxit, piv, Pi, Phi, modBasic, profile, profile_pars) {
    .Call(`_estDLVM_HMcat_TEM`, S, yv, k, tol_lk, tol_theta, maxit, piv, Pi, Phi, modBasic, profile, profile_pars)
}

HMcat_Initialization_step <- function(S, yv, ns, r, TT, k, n_parents) {
    .Call(`_estDLVM_HMcat_Initialization_step`, S, yv, ns, r, TT, k, n_parents)
}

HMcat_ME_step <- function(S, yv, k, tol_lk, tol_theta, maxit, P, modBasic) {
    .Call(`_estDLVM_HMcat_ME_step`, S, yv, k, tol_lk, tol_theta, maxit, P, modBasic)
}

HMcat_LastME_step <- function(S, yv, k, tol_lk, tol_theta, maxit, P, modBasic) {
    .Call(`_estDLVM_HMcat_LastME_step`, S, yv, k, tol_lk, tol_theta, maxit, P, modBasic)
}

HMcat_CrossOver_step <- function(ns, TT, P, n_children, n_parents) {
    .Call(`_estDLVM_HMcat_CrossOver_step`, ns, TT, P, n_children, n_parents)
}

HMcat_Selection_step <- function(PV_p, PV_c, fit_p, fit_c, n_parents, n_children) {
    .Call(`_estDLVM_HMcat_Selection_step`, PV_p, PV_c, fit_p, fit_c, n_parents, n_children)
}

HMcat_Mutation_step <- function(ns, TT, k, P, prob_mut) {
    .Call(`_estDLVM_HMcat_Mutation_step`, ns, TT, k, P, prob_mut)
}

HMcat_EEM <- function(S, yv, k, tol_lk, tol_theta, maxit, modBasic, n_parents, n_children, prob_mut, R) {
    .Call(`_estDLVM_HMcat_EEM`, S, yv, k, tol_lk, tol_theta, maxit, modBasic, n_parents, n_children, prob_mut, R)
}

HMcont_Temperature <- function(h, profile, profile_pars) {
    .Call(`_estDLVM_HMcont_Temperature`, h, profile, profile_pars)
}

dmvnorm <- function(x, mean, sigma) {
    .Call(`_estDLVM_dmvnorm`, x, mean, sigma)
}

HMcont_ComputeLogLik <- function(S, piv, Pi, Mu, Si) {
    .Call(`_estDLVM_HMcont_ComputeLogLik`, S, piv, Pi, Mu, Si)
}

HMcont_CheckConvergence <- function(lk, lk_old, piv, Pi, Mu, Si, piv_old, Pi_old, Mu_old, Si_old, it, tol_lk, tol_theta, maxit) {
    .Call(`_estDLVM_HMcont_CheckConvergence`, lk, lk_old, piv, Pi, Mu, Si, piv_old, Pi_old, Mu_old, Si_old, it, tol_lk, tol_theta, maxit)
}

HMcont_E_step <- function(n, TT, k, llk_list, Pi) {
    .Call(`_estDLVM_HMcont_E_step`, n, TT, k, llk_list, Pi)
}

HMcont_TE_step <- function(n, TT, k, llk_list, Pi, temp) {
    .Call(`_estDLVM_HMcont_TE_step`, n, TT, k, llk_list, Pi, temp)
}

HMcont_M_step <- function(Sv, n, r, TT, k, E_list, modBasic) {
    .Call(`_estDLVM_HMcont_M_step`, Sv, n, r, TT, k, E_list, modBasic)
}

HMcont_EM <- function(S, k, tol_lk, tol_theta, maxit, piv, Pi, Mu, Si, modBasic) {
    .Call(`_estDLVM_HMcont_EM`, S, k, tol_lk, tol_theta, maxit, piv, Pi, Mu, Si, modBasic)
}

HMcont_TEM <- function(S, k, tol_lk, tol_theta, maxit, piv, Pi, Mu, Si, modBasic, profile, profile_pars) {
    .Call(`_estDLVM_HMcont_TEM`, S, k, tol_lk, tol_theta, maxit, piv, Pi, Mu, Si, modBasic, profile, profile_pars)
}

HMcont_Initialization_step <- function(S, n, r, TT, k, n_parents) {
    .Call(`_estDLVM_HMcont_Initialization_step`, S, n, r, TT, k, n_parents)
}

HMcont_ME_step <- function(S, k, tol_lk, tol_theta, maxit, P, modBasic) {
    .Call(`_estDLVM_HMcont_ME_step`, S, k, tol_lk, tol_theta, maxit, P, modBasic)
}

HMcont_LastME_step <- function(S, k, tol_lk, tol_theta, maxit, P, modBasic) {
    .Call(`_estDLVM_HMcont_LastME_step`, S, k, tol_lk, tol_theta, maxit, P, modBasic)
}

HMcont_CrossOver_step <- function(n, TT, P, n_children, n_parents) {
    .Call(`_estDLVM_HMcont_CrossOver_step`, n, TT, P, n_children, n_parents)
}

HMcont_Selection_step <- function(PV_p, PV_c, fit_p, fit_c, n_parents, n_children) {
    .Call(`_estDLVM_HMcont_Selection_step`, PV_p, PV_c, fit_p, fit_c, n_parents, n_children)
}

HMcont_Mutation_step <- function(n, TT, k, P, prob_mut) {
    .Call(`_estDLVM_HMcont_Mutation_step`, n, TT, k, P, prob_mut)
}

HMcont_EEM <- function(S, k, tol_lk, tol_theta, maxit, modBasic, n_parents, n_children, prob_mut, R) {
    .Call(`_estDLVM_HMcont_EEM`, S, k, tol_lk, tol_theta, maxit, modBasic, n_parents, n_children, prob_mut, R)
}

LC_Temperature <- function(h, profile, profile_pars) {
    .Call(`_estDLVM_LC_Temperature`, h, profile, profile_pars)
}

LC_CheckConvergence <- function(lk, lk_old, piv, Phi, piv_old, Phi_old, it, tol_lk, tol_theta, maxit) {
    .Call(`_estDLVM_LC_CheckConvergence`, lk, lk_old, piv, Phi, piv_old, Phi_old, it, tol_lk, tol_theta, maxit)
}

LC_EM_step <- function(S, yv, C, ns, r, n, k, piv, Piv, Psi, Phi) {
    .Call(`_estDLVM_LC_EM_step`, S, yv, C, ns, r, n, k, piv, Piv, Psi, Phi)
}

LC_TEM_step <- function(S, yv, C, ns, r, n, k, piv, Piv, Psi, Phi, temp) {
    .Call(`_estDLVM_LC_TEM_step`, S, yv, C, ns, r, n, k, piv, Piv, Psi, Phi, temp)
}

LC_EM <- function(S, yv, k, tol_lk, tol_theta, maxit, piv, Piv, Psi, Phi) {
    .Call(`_estDLVM_LC_EM`, S, yv, k, tol_lk, tol_theta, maxit, piv, Piv, Psi, Phi)
}

LC_TEM <- function(S, yv, k, tol_lk, tol_theta, maxit, piv, Piv, Psi, Phi, profile, profile_pars) {
    .Call(`_estDLVM_LC_TEM`, S, yv, k, tol_lk, tol_theta, maxit, piv, Piv, Psi, Phi, profile, profile_pars)
}

LC_Initialization_step <- function(S, yv, ns, r, C, k, n_parents) {
    .Call(`_estDLVM_LC_Initialization_step`, S, yv, ns, r, C, k, n_parents)
}

LC_ME_step <- function(S, yv, ns, n, r, C, V, k, maxit, tol_lk, tol_theta) {
    .Call(`_estDLVM_LC_ME_step`, S, yv, ns, n, r, C, V, k, maxit, tol_lk, tol_theta)
}

LC_LastME_step <- function(S, yv, ns, n, r, C, V, k, maxit, tol_lk, tol_theta) {
    .Call(`_estDLVM_LC_LastME_step`, S, yv, ns, n, r, C, V, k, maxit, tol_lk, tol_theta)
}

LC_CrossOver_step <- function(ns, P, n_children, n_parents) {
    .Call(`_estDLVM_LC_CrossOver_step`, ns, P, n_children, n_parents)
}

LC_Selection_step <- function(PV_p, PV_c, fit_p, fit_c, n_parents, n_children) {
    .Call(`_estDLVM_LC_Selection_step`, PV_p, PV_c, fit_p, fit_c, n_parents, n_children)
}

LC_Mutation_step <- function(ns, k, V, prob_mut) {
    .Call(`_estDLVM_LC_Mutation_step`, ns, k, V, prob_mut)
}

LC_EEM <- function(S, yv, k, tol_lk, tol_theta, maxit, n_parents, n_children, prob_mut, R) {
    .Call(`_estDLVM_LC_EEM`, S, yv, k, tol_lk, tol_theta, maxit, n_parents, n_children, prob_mut, R)
}

